DROP TABLE IF EXISTS city CASCADE;
CREATE TABLE IF NOT EXISTS city
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS color CASCADE;
CREATE TABLE IF NOT EXISTS color
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS manufacturer CASCADE;
CREATE TABLE IF NOT EXISTS manufacturer
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);


DROP TABLE IF EXISTS driver CASCADE;
CREATE TABLE IF NOT EXISTS driver
(
    driver_id      bigint generated by default as identity,
    first_name     varchar(255),
    last_name      varchar(255),
    birth_date     date,
    city_id        bigint,
    primary key (driver_id)
);

DROP TABLE IF EXISTS company_car CASCADE;
CREATE TABLE IF NOT EXISTS company_car
(
    id                   bigint generated by default as identity,
    licence_plate_number varchar(255),
    color_id             bigint,
    manufacturer_id      bigint,
    model                varchar(255),
    driver_driver_id     bigint,
    in_use_since         date,
    repair_required      boolean,
    primary key (id)
);


alter table company_car
    add constraint FK5sdhc6m3ebkj1d0cvb3jylp8b foreign key (color_id) references color;
alter table company_car
    add constraint FKn77y70j8qb5c1x8x471fo66ky foreign key (driver_driver_id) references driver;
alter table company_car
    add constraint FKtm0exnla5s3cyvfq5ji3orv6g foreign key (manufacturer_id) references manufacturer;
alter table driver
    add constraint FK7tw2pbwu4keglfx2rq6hn0war foreign key (city_id) references city;

